# Generated by Django 5.2.5 on 2025-08-08 15:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('library_branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('days_borrowed', models.PositiveIntegerField(blank=True, null=True)),
                ('was_overdue', models.BooleanField(default=False)),
                ('fine_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('renewed', 'Renewed'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='borrowed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_history', to='books.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_history', to='library_branches.librarybranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrowing History',
                'verbose_name_plural': 'Borrowing Histories',
                'ordering': ['-borrowed_date'],
            },
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('max_renewals_allowed', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='books.bookcopy')),
                ('librarian_issued', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL)),
                ('librarian_returned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent Condition'), ('good', 'Good Condition'), ('fair', 'Fair Condition'), ('poor', 'Poor Condition'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='good', max_length=20)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('borrow_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='borrowing.borrowtransaction')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
    ]
