# Generated by Django 5.2.5 on 2025-08-08 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField()),
                ('total_capacity', models.PositiveIntegerField(help_text='Maximum number of books this branch can hold')),
                ('wifi_available', models.BooleanField(default=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('accessible_entrance', models.BooleanField(default=True)),
                ('study_rooms', models.PositiveIntegerField(default=0)),
                ('computer_stations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('special_hours_note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='library_branches.librarybranch')),
            ],
            options={
                'ordering': ['branch', 'weekday'],
                'unique_together': {('branch', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='LibrarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('reference', 'Reference'), ('periodicals', 'Periodicals'), ('children', "Children's Section"), ('young_adult', 'Young Adult'), ('local_authors', 'Local Authors'), ('digital', 'Digital Collection'), ('rare_books', 'Rare Books'), ('study_materials', 'Study Materials')], max_length=20)),
                ('floor_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('shelf_range_start', models.CharField(help_text='Starting shelf identifier', max_length=10)),
                ('shelf_range_end', models.CharField(help_text='Ending shelf identifier', max_length=10)),
                ('is_restricted', models.BooleanField(default=False, help_text='Requires special permission to access')),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('security_level', models.CharField(choices=[('low', 'Low Security'), ('medium', 'Medium Security'), ('high', 'High Security')], default='low', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of books in this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='library_branches.librarybranch')),
            ],
            options={
                'ordering': ['branch', 'floor_number', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
